name: senibara
description: A Senibara package project. This package holds a series of custom data, widgets, and utilities for reuse by employees of Senibara.
version: 0.0.3
homepage: https://github.com/TekenaTariah/senibara_package

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^1.4.2 #https://pub.dev/packages/package_info_plus
  google_fonts: ^2.3.1 #https://pub.dev/packages/google_fonts todo: enable on ios(read doc)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - packages/senibara/assets/logos/logo-ht.png
    - packages/senibara/assets/logos/logo-vt.png
    - packages/senibara/assets/logos/logo-st.png
    - packages/senibara/assets/images/gradient_line.png